export const FETCH_VOYAGES_FAILURE = 'FETCH_VOYAGES_FAILURE'
export const FETCH_VOYAGES_REQUEST = 'FETCH_VOYAGES_REQUEST'
export const FETCH_VOYAGES_SUCCESS = 'FETCH_VOYAGES_SUCCESS'
export const VOYAGE_SELECTED_CHANGED='VOYAGE_SELECTED_CHANGED'