
export const FETCH_EQUIPMENTS_FAILURE = 'FETCH_EQUIPMENTS_FAILURE'
export const FETCH_EQUIPMENTS_REQUEST = 'FETCH_EQUIPMENTS_REQUEST'
export const FETCH_EQUIPMENTS_SUCCESS = 'FETCH_EQUIPMENTS_SUCCESS'
export const EQUIPMENT_SELECTED_CHANGED='EQUIPMENT_SELECTED_CHANGED'